_wandb:
    value:
        cli_version: 0.28.0
        e:
            1t4w0c1fif3wupw9u0qjvarw6k3db2gt:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    macModel: Mac14,10
                    memoryGb: 32
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                args:
                    - --mode
                    - train
                    - --frame_dir
                    - HMDB51
                    - --n_classes
                    - "51"
                    - --batch_size
                    - "4"
                    - --model_type
                    - lrcn
                    - --cnn_backbone
                    - resnet34
                    - --pretrained
                    - "True"
                    - --fr_per_vid
                    - "16"
                    - --rnn_hidden_size
                    - "256"
                    - --rnn_n_layers
                    - "2"
                    - --dropout
                    - "0.3"
                    - --learning_rate
                    - "0.00003"
                    - --n_epochs
                    - "30"
                codePath: run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "979047972864"
                email: jhenso13@jh.edu
                executable: /opt/homebrew/anaconda3/envs/assignment4/bin/python
                git:
                    commit: 27f060e70dc28658fe6768e17c3377fbbb432749
                    remote: https://github.com/JessicaHenson01/Assignment-4.git
                host: Jessicas-MacBook-Pro-2.local
                memory:
                    total: "34359738368"
                os: macOS-26.5.2-arm64-arm-64bit
                program: /Users/jessicahenson/Desktop/Assignment 4 - Video Action Recognition/run.py
                python: CPython 3.12.13
                root: /Users/jessicahenson/Desktop/Assignment 4 - Video Action Recognition
                startedAt: "2026-07-16T06:19:44.097550Z"
                writerId: 1t4w0c1fif3wupw9u0qjvarw6k3db2gt
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 16
            "4": 3.12.13
            "5": 0.28.0
            "12": 0.28.0
            "13": darwin-arm64
backbone:
    value: resnet34
batch_size:
    value: 4
dropout:
    value: 0.3
epochs:
    value: 30
frames_per_video:
    value: 16
hidden_size:
    value: 256
learning_rate:
    value: 3e-05
lstm_layers:
    value: 2
